### ISSUE TITLE
Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by dzg** [turt2live/matrix-bot-sdk#203]
Every few hours I get these errors:

```
MatrixHttpClient (REQ-1571) Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/zeev/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:509:28)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:763:9)
    at Object.onceWrapper (node:events:509:28)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
MatrixClientLite Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/zeev/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:509:28)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:763:9)
    at Object.onceWrapper (node:events:509:28)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
```

Is this cause for alarm? Any way to fix? Or suppress?

Thanks

**Comment by turt2live** [comment]
This is a network issue between the bot and the homeserver - I would suggest ensuring the homeserver itself is healthy, and that the connection is stable.

**Comment by dzg** [comment]
Hm, the 'homeserver' in this case is [`https://matrix-client.matrix.org`](https://matrix-client.matrix.org) ... and the bot is running on my local Mac.

Any way to 'catch' these errors? Can I ignore them?
