### ISSUE TITLE
Error: Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-darwin-x64'

### ISSUE THREAD

**Issue by alexohneander** [turt2live/matrix-bot-sdk#274]
After I create the example project and start it, I get this error message:
```
Error: Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-darwin-x64'
Require stack:
- /Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js
- /Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/matrix-bot-sdk/lib/e2ee/CryptoClient.js
- /Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/matrix-bot-sdk/lib/index.js
- /Users/alex/Projects/NodeJS/matrix-news-bot/src/bot.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:111:29)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._compile (/Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/fg/jx5d6_2n7yl0f4d4d6n5lb5r0000gn/T/ts-node-dev-hook-018211916685773932.js:114:20)
    at Object.nodeDevHook [as .js] (/Users/alex/Projects/NodeJS/matrix-news-bot/node_modules/ts-node-dev/lib/hook.js:63:13)
```

I tried to install the dependency, but unfortunately that did not help.

**Comment by turt2live** [comment]
Usually this means you don't have the toolchain to build the dependency (rust) or the upstream package doesn't offer it. In either case, it'd be a https://github.com/matrix-org/matrix-rust-sdk issue
