### ISSUE TITLE
Version `GLIBC_2.29' not found.

### ISSUE THREAD

**Issue by ostov-larion** [turt2live/matrix-bot-sdk#326]
Example code from https://turt2live.github.io/matrix-bot-sdk/tutorial-bot.html doesnt working.

```
/home/ostov/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:250
    throw loadError
    ^

Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/ostov/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/matrix-sdk-crypto.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/ostov/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:188:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

```

OS: elementary OS 5.1.7 Hera

**Comment by turt2live** [comment]
You'll need the build dependencies for compiling/running Rust code as well: https://www.rust-lang.org/
